PackageIdentifier: 7zip.7zip
PackageName: 7Zip
Moniker: 7zip
PackageVersion: 16.0.4
Publisher: 7zip
Author: 7zip
License: Copyright (C) 1999-2020 Igor Pavlov. - GNU LGPL
LicenseUrl: https://7-zip.org/license.txt
MinimumOSVersion: 10.0.0.0
PackageUrl: https://www.7-zip.org/
ShortDescription: Free and open source file archiver with a high compression ratio.
Tags:
- 7zip
- compression
- file compression
- utility
- tool
- zip
InstallerType: msi
Installers:
- Architecture: x64
  InstallerSha256: 121B729EAA36DD5D20BB2044E2543B60FBEAE99F3EA208A1720CE2FF03C7FA98
  InstallerType: wix
  InstallerUrl: https://winget-cache-test-fccxhrb9evdxdrem.b02.azurefd.net/tests/installers/esrp-potential-malware.msi
  ProductCode: '{EE9DED09-83F6-400F-BCE5-960E87D3D2BA}'
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
