PackageIdentifier: IntegrationTests.UrlValidation.InstallerUnavailable
PackageName: Foo Installer
Moniker: Foo
PackageVersion: 1.0
Publisher: Foo Labs
Author: Bar
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinimumOSVersion: 10.0.0.0
Tags:
- Foo
- Foo Labs
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://winget-cache-test-fccxhrb9evdxdrem.b02.azurefd.net/tests/installers/seriously-dont-make-a-real-installer-here.msi
  InstallerSha256: 09eebc165474969deea115a3cb6a3b88ca206e2c65975e76e6b7d891d1d6e648
ShortDescription: Test for installer that doesn't exist.
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.5.0
